travis:
  secure:
    BINSTAR_TOKEN: I4TDuly9TOIEEUVMfvthkBtz33hmk9Ab+3acY8OwTIldMdvZi3tfsGe5eYCj5m/77fJEmqaNbjWVEGsjXjvMkAUAuA0GDPBTxgO+829w/6R0BIrIuDw+ihx+6xeDkLPif6PIlHziTx89RFFC6/OuIEOX0qYPOE1MhszLV7HzBPR0sRSQz6WT4zBjkXDGfI0omigZW2pajN3zPFVwkaREf2/YjqoiLp8vSEvY+s8jSEpe/v+vp5DNb+g0kgEBT+vflcj5xVJfaIShDhCiFGbU7weNdwQCOI9UU0jaBPqbPpkW/Hvp1lmvYpNd1ZEodZuQcur89xk6Klx92d2lnWlUMriP4wT3m9RkUDOc6OIakGipHyZDebPEBFYE/KQ5j7GWv136fgZ7nkanYaBHmkDGPTjHabaTTTnniziGhmdkdE+gxu1d+WE868beeVGFiDk8+TdOD+6zaW/GQRSk8Q0WGGCad43HVsykCC0uJJvLR1DWGNR0Osa5y+jawnXPFjUWFEOLhNThLIdZ+Vk3fKdBbQAL3fd/3q4v5OVq2S4SywmDtFqwbUosrVRCaXJ4q9f1l8Nkg0CPRPpe8kunRGjqDY/LD4MFtKi2BmmypVlHWJ4hes2+QjJgKU1ONIme7hv8lV/vVMMmp19YfW68v+MWO6ZsaWDe0uQix95sknRw8qk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
